# -----------------------------------------------------------
# Stage 1: Build (Compilazione)
# -----------------------------------------------------------
FROM node:lts-alpine AS builder

WORKDIR /app

COPY frontend/ .

RUN npm install

RUN npm run build

# -----------------------------------------------------------
# Stage 2: Runtime (Server Nginx)
# -----------------------------------------------------------
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]