<template>
    <div class="highlighter-container">
        <div class="toolbar" v-if="labels.length > 0">
            <span class="toolbar-label">Select Label:</span>
            <button v-for="label in labels" :key="label.name" :style="{
                backgroundColor: selectedLabel === label.name ? label.color : '#f0f0f0',
                color: selectedLabel === label.name ? 'white' : 'black',
                borderColor: label.color
            }" class="label-btn" @click="selectedLabel = label.name">
                {{ label.name }}
            </button>
        </div>

        <div class="text-area" ref="textRef" @mouseup="handleSelection">
            <template v-for="(chunk, index) in renderChunks" :key="index">
                <span v-if="chunk.isHighlight" class="highlight"
                    :style="{ backgroundColor: getLabelColor(chunk.label) }">{{ chunk.text }}<button class="remove-btn"
                        @click.stop="removeSpan(chunk.id)">×</button></span>
                <span v-else>{{ chunk.text }}</span>
            </template>
        </div>

        <!-- Popup Modal -->
        <div v-if="showPopup" class="popup-overlay" @click.self="closePopup">
            <div class="popup-content">
                <p class="popup-message">{{ popupMessage }}</p>
                <button class="popup-close-btn" @click="closePopup">OK</button>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue';

const props = defineProps({
    text: String,
    labels: Array,
    spans: {
        type: Array,
        default: () => []
    }
});

const emit = defineEmits(['update:spans']);

const selectedLabel = ref(null);
const textRef = ref(null);

// Popup State
const showPopup = ref(false);
const popupMessage = ref("");

const openPopup = (msg) => {
    popupMessage.value = msg;
    showPopup.value = true;
};

const closePopup = () => {
    showPopup.value = false;
};

watch(() => props.labels, (newLabels) => {
    if (newLabels && newLabels.length > 0 && !selectedLabel.value) {
        selectedLabel.value = newLabels[0].name;
    }
}, { immediate: true });


// This function calculates the *absolute* character offset of the user's cursor
// relative to the start of the text container.
// Why is this hard? Because the DOM contains hidden nodes, button elements (the 'x'),
// and layout whitespace that are NOT part of the raw text string.

const getGlobalOffset = (root, targetNode, targetOffset) => {
    let offset = 0;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
        acceptNode: (node) => {
            // Ignore text nodes inside buttons (the "x")
            // and any whitespace generated by the layout if not part of the text
            if (node.parentNode && node.parentNode.classList.contains('remove-btn')) {
                return NodeFilter.FILTER_REJECT;
            }
            return NodeFilter.FILTER_ACCEPT;
        }
    });

    while (walker.nextNode()) {
        const node = walker.currentNode;
        if (node === targetNode) {
            return offset + targetOffset;
        }
        offset += node.nodeValue.length;
    }
    return -1; // Not found
};

const handleSelection = () => {
    const selection = window.getSelection();
    if (selection.rangeCount === 0 || selection.isCollapsed) return;

    const range = selection.getRangeAt(0);
    const container = textRef.value;

    // 1. Verify that the selection is inside our container
    if (!container.contains(range.commonAncestorContainer)) {
        selection.removeAllRanges();
        return;
    }

    // 2. Calculate global Start and End using the robust function
    const start = getGlobalOffset(container, range.startContainer, range.startOffset);
    const end = getGlobalOffset(container, range.endContainer, range.endOffset);

    // If something went wrong in calculation, exit
    if (start === -1 || end === -1) {
        selection.removeAllRanges();
        return;
    }

    // 3. Normalize (if the user selected from right to left)
    let realStart = Math.min(start, end);
    let realEnd = Math.max(start, end);
    let textSegment = props.text.slice(realStart, realEnd);

    // 4. Whitespace Check and Trimming
    // CONFIGURATION NOTE: Comment out this block to allow selecting empty spaces.
    if (!textSegment.trim()) {
        selection.removeAllRanges();
        return;
    }

    // 4b. Remove leading/trailing whitespace from selection
    // CONFIGURATION NOTE: Remove these calculations to keep original selection with spaces.
    const leadingSpaces = textSegment.length - textSegment.trimStart().length;
    const trailingSpaces = textSegment.length - textSegment.trimEnd().length;

    realStart += leadingSpaces;
    realEnd -= trailingSpaces;
    textSegment = textSegment.trim();

    // 5. Label Check
    if (!selectedLabel.value) {
        openPopup("Please select a label first!");
        selection.removeAllRanges();
        return;
    }

    // ----------------------------------------------------------------------------------
    // BUSINESS LOGIC: VALIDATION / LOGICA DI BUSINESS: VALIDAZIONE
    // ----------------------------------------------------------------------------------

    // EN: 1. Prevent Overlaps: Crucial for data quality. Overlapping entities are ambiguous.
    // IT: 1. Prevenire Sovrapposizioni: Cruciale per la qualità dei dati. Entità sovrapposte sono ambigue.
    const hasOverlap = props.spans.some(span => {
        return (realStart < span.end && realEnd > span.start);
    });

    if (hasOverlap) {
        openPopup("Warning: You cannot overlap highlights. Remove the old one first.");
        selection.removeAllRanges();
        return;
    }

    // EN: 2. Create Annotation Object: Standardized format for backend storage.
    // IT: 2. Creare Oggetto Annotazione: Formato standardizzato per il salvataggio backend.
    const newSpan = {
        start: realStart,
        end: realEnd,
        label: selectedLabel.value,
        text: textSegment,
        id: Date.now()
    };

    emit('update:spans', [...props.spans, newSpan]);
    selection.removeAllRanges();
};

const removeSpan = (spanId) => {
    const filtered = props.spans.filter(s => s.id !== spanId);
    emit('update:spans', filtered);
};

const getLabelColor = (labelName) => {
    const l = props.labels.find(x => x.name === labelName);
    return l ? l.color : '#ccc';
};

// Chunk rendering (Remains the same, works well)
const renderChunks = computed(() => {
    if (!props.text) return [];

    const sortedSpans = [...props.spans].sort((a, b) => a.start - b.start);
    const chunks = [];
    let currentIndex = 0;

    sortedSpans.forEach(span => {
        if (span.start > currentIndex) {
            chunks.push({
                text: props.text.slice(currentIndex, span.start),
                isHighlight: false
            });
        }

        chunks.push({
            text: props.text.slice(span.start, span.end),
            isHighlight: true,
            label: span.label,
            id: span.id
        });

        currentIndex = span.end;
    });

    if (currentIndex < props.text.length) {
        chunks.push({
            text: props.text.slice(currentIndex),
            isHighlight: false
        });
    }

    return chunks;
});
</script>

<style scoped>
.highlighter-container {
    display: flex;
    flex-direction: column;
    gap: 10px;
}

.toolbar {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
    padding: 10px;
    background: #f8f9fa;
    border-radius: 8px;
    border: 1px solid #dee2e6;
    align-items: center;
}

.label-btn {
    padding: 6px 12px;
    border: 2px solid transparent;
    border-radius: 20px;
    cursor: pointer;
    font-weight: bold;
    font-size: 0.9rem;
    transition: all 0.2s;
}

.label-btn:hover {
    opacity: 0.8;
}

.text-area {
    font-size: 1.2rem;
    line-height: 1.8;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 8px;
    background: white;
    min-height: 150px;
    white-space: pre-wrap;
    cursor: text;
}

.highlight {
    padding: 2px 0;
    border-radius: 4px;
    position: relative;
    margin: 0 2px;
    cursor: pointer;
}

.remove-btn {
    position: absolute;
    top: -10px;
    right: -10px;
    width: 18px;
    height: 18px;
    background: #ff4444;
    color: white;
    border: 2px solid white;
    border-radius: 50%;
    font-size: 12px;
    display: none;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    z-index: 10;
    padding: 0;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}

.highlight:hover .remove-btn {
    display: flex;
}

/* POPUP STYLES */
.popup-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 1000;
}

.popup-content {
    background: white;
    padding: 25px;
    border-radius: 12px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
    text-align: center;
    max-width: 400px;
    width: 90%;
    animation: fadeIn 0.2s ease-out;
}

.popup-message {
    margin-bottom: 20px;
    font-size: 1.1rem;
    color: #333;
}

.popup-close-btn {
    padding: 8px 24px;
    background: #007bff;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: bold;
    transition: background 0.2s;
}

.popup-close-btn:hover {
    background: #0056b3;
}

@keyframes fadeIn {
    from {
        opacity: 0;
        transform: translateY(-10px);
    }

    to {
        opacity: 1;
        transform: translateY(0);
    }
}
</style>