# Generated by Django 6.0.2 on 2026-02-10 07:47

import annotation.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prolific_pid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('consent_accepted', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('target_tasks', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('configuration', models.JSONField(default=annotation.models.get_default_configuration, help_text='Frontend configuration (labels, colors, UI settings)')),
                ('configuration_file', models.FileField(blank=True, help_text='Opzionale: Carica un file JSON per sovrascrivere la configurazione.', null=True, upload_to='configs/')),
                ('distribution_strategy', models.CharField(choices=[('STANDARD', 'Standard (Pool Pubblico)'), ('FULL_OVERLAP', 'Tutti vedono tutto (Alta Ridondanza)'), ('METADATA_MATCH', 'Assegnazione per Gruppi (Metadata Based)')], default='STANDARD', help_text='Definisce come i documenti vengono assegnati agli annotatori.', max_length=20)),
                ('min_annotations_per_doc', models.IntegerField(default=3, help_text='Obiettivo: Quante persone devono annotare ogni documento.')),
                ('max_annotations_per_doc', models.IntegerField(default=5, help_text='Hard Cap: Smetti di servire il documento se raggiunge questo numero (evita sprechi).')),
                ('prioritize_unannotated', models.BooleanField(default=True, help_text='Se True, il sistema cercherà di finire prima i documenti mai visti.')),
                ('dataset_file', models.FileField(blank=True, help_text='Upload a .jsonl file to automatically populate documents.', null=True, upload_to='datasets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_gold_unit', models.BooleanField(default=False)),
                ('gold_solution', models.JSONField(blank=True, default=dict, null=True)),
                ('min_annotations_required', models.IntegerField(default=3)),
                ('current_annotations_count', models.IntegerField(db_index=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='annotation.project')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('milliseconds_to_complete', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='annotation.annotator')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.document')),
            ],
            options={
                'unique_together': {('document', 'annotator')},
            },
        ),
    ]
