# Generated by Django 6.0.2 on 2026-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_gold_units',
            field=models.BooleanField(default=True, help_text='If True, gold units will be injected for quality control during annotation.'),
        ),
        migrations.AddField(
            model_name='project',
            name='enable_screening',
            field=models.BooleanField(default=True, help_text='If True, annotators will see the screening questionnaire before the task.'),
        ),
    ]
