# Generated by Django 6.0.2 on 2026-02-28 15:38

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScreeningUnitProxy',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_screening_unit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screening_units_file',
        ),
        migrations.AlterField(
            model_name='project',
            name='gold_units_file',
            field=models.FileField(blank=True, help_text='Upload a .jsonl file for GOLD units (Quality Control Injection).', null=True, upload_to='datasets/gold/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screening_config',
            field=models.JSONField(blank=True, default=annotation.models.get_default_configuration_for_screening, help_text="Configuration for quality control: { 'min_accuracy_required': float, 'gold_injection_frequency': int }"),
        ),
    ]
