# Generated by Django 6.0.2 on 2026-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='exclude_from_distribution',
            field=models.BooleanField(default=False),
        ),
    ]
