# Generated by Django 6.0.2 on 2026-02-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectenrollment',
            name='survey_data',
        ),
    ]
