# Generated by Django 6.0.2 on 2026-03-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='block_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Used to group documents into blocks for the SAME_ANNOTATORS strategy', null=True),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='assigned_block_id',
            field=models.IntegerField(blank=True, help_text='The document block assigned to this annotator (for SAME_ANNOTATORS).', null=True),
        ),
    ]
