# Generated by Django 6.0.2 on 2026-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unique Identifier for the URL (e.g., 'nome-studio')", max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='distribution_strategy',
            field=models.CharField(choices=[('STANDARD', 'Standard (Public Pool) - Randomly assign documents to annotators'), ('FULL_OVERLAP', 'Everyone sees everything (High Redundancy) - All annotators see all documents'), ('SAME_ANNOTATORS', 'Same k annotators view the same document')], default='STANDARD', help_text='Defines how documents are assigned to annotators.', max_length=20),
        ),
    ]
