# Generated by Django 6.0.2 on 2026-03-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
    ]
