# Generated by Django 6.0.2 on 2026-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='is_test',
            field=models.BooleanField(default=False, help_text='If True, this is a test/admin session and should be excluded from metrics.'),
        ),
    ]
