# Generated by Django 6.0.2 on 2026-05-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentproxy',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Annotation Document', 'verbose_name_plural': 'Annotation Documents'},
        ),
    ]
