# Generated by Django 6.0.2 on 2026-05-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_documentproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldunitproxy',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Gold Unit', 'verbose_name_plural': 'Gold Units'},
        ),
    ]
