# Generated by Django 6.0.2 on 2026-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_remove_project_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gold_config',
        ),
        migrations.AddField(
            model_name='project',
            name='continuous_exclusion',
            field=models.BooleanField(default=False, help_text='If True, the annotator is excluded as soon as they drop below the threshold.'),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_strategy',
            field=models.CharField(choices=[('percentage', 'Percentage Based - use cumulative accuracy'), ('strikes', 'Strike Based - use consecutive wrong answers'), ('hybrid', 'Hybrid - use both percentage and strikes')], default='percentage', help_text='The strategy used to evaluate annotator quality.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='gold_injection_frequency',
            field=models.IntegerField(default=5, help_text='Frequency of gold task injection (e.g., 1 every 5 tasks).'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_strikes',
            field=models.IntegerField(default=3, help_text="For 'strikes' or 'hybrid' strategy: max consecutive wrong answers."),
        ),
        migrations.AddField(
            model_name='project',
            name='min_accuracy_required',
            field=models.FloatField(default=0.6, help_text='Minimum accuracy required for gold tasks (0.0 to 1.0).'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_gold_before_eval',
            field=models.IntegerField(default=3, help_text='Min gold units completed before starting evaluation.'),
        ),
    ]
