# Generated by Django 6.0.2 on 2026-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_annotator_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_test',
            field=models.BooleanField(default=False, help_text='If True, this annotation was made in test mode.'),
        ),
    ]
