# Generated by Django 6.0.2 on 2026-03-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_document_block_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotators_per_block',
            field=models.IntegerField(default=3, help_text='SAME_ANNOTATORS strategy: Number of distinct annotators assigned to each block.'),
        ),
        migrations.AddField(
            model_name='project',
            name='block_size',
            field=models.IntegerField(default=10, help_text='SAME_ANNOTATORS strategy: Number of documents injected into each block.'),
        ),
    ]
