# Generated by Django 6.0.2 on 2026-03-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_remove_project_gold_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='continuous_exclusion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='evaluation_strategy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_strikes',
        ),
    ]
