# Generated by Django 6.0.2 on 2026-03-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_project_annotators_per_block_project_block_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='target_tasks_per_annotator',
        ),
        migrations.RemoveField(
            model_name='projectenrollment',
            name='target_tasks',
        ),
    ]
