# Generated by Django 6.0.2 on 2026-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_remove_project_continuous_exclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_practice_task',
            field=models.BooleanField(default=True, help_text='If True, annotators will see a practice task before starting the real task.'),
        ),
    ]
