# Generated by Django 6.0.2 on 2026-03-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_remove_project_target_tasks_per_annotator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='launched_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the project was first set to LIVE.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='DRAFT', help_text='Current lifecycle state of the project.', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='distribution_strategy',
            field=models.CharField(choices=[('STANDARD', 'Standard - Randomly assign documents to annotators'), ('FULL_OVERLAP', 'Everyone sees everything (High Redundancy) - All annotators see all documents'), ('SAME_ANNOTATORS', 'Same k annotators view the same document (Low Redundancy) - the annotators are assigned to blocks of documents')], default='STANDARD', help_text='Defines how documents are assigned to annotators.', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If False, the project will not accept new annotations (Pause mode).'),
        ),
        migrations.CreateModel(
            name='ProjectLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text="The event type (e.g., 'Project Launched', 'Status Changed', 'Data Imported')", max_length=100)),
                ('details', models.TextField(blank=True, help_text='Optional details or message.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='annotation.project')),
            ],
            options={
                'verbose_name': 'Project Log Entry',
                'verbose_name_plural': 'Project Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
